//	撲克牌_正面向下
var PokerDeck_Up ={
    spade1: { index: 5, name: "spade1"},
    spade2: { index: 33, name: "spade2" },
    spade3: { index: 41, name: "spade3" },
    spade4: { index: 29, name: "spade4" },
    spade5: { index: 49, name: "spade5" },
    spade6: { index: 37, name: "spade6" },
    spade7: { index: 25, name: "spade7" },
    spade8: { index: 45, name: "spade8" },
    spade9: { index: 21, name: "spade9" },
    spade10: { index: 1, name: "spade10" },
    spade11: { index: 9, name: "spade11" },
    spade12: { index: 13, name: "spade12" },
    spade13: { index: 17, name: "spade13" },

    heart1: { index: 52, name: "heart1" },
    heart2: { index: 19, name: "heart2" },
    heart3: { index: 47, name: "heart3" },
    heart4: { index: 40, name: "heart4" },
    heart5: { index: 6, name: "heart5" },
    heart6: { index: 11, name: "heart6" },
    heart7: { index: 42, name: "heart7" },
    heart8: { index: 26, name: "heart8" },
    heart9: { index: 22, name: "heart9" },
    heart10: { index: 12, name: "heart10" },
    heart11: { index: 27, name: "heart11" },
    heart12: { index: 30, name: "heart12" },
    heart13: { index: 3, name: "heart13" },

    club1: { index: 7, name: "club1" },
    club2: { index: 43, name: "club2" },
    club3: { index: 35, name: "club3" },
    club4: { index: 20, name: "club4" },
    club5: { index: 24, name: "club5" },
    club6: { index: 15, name: "club6" },
    club7: { index: 38, name: "club7" },
    club8: { index: 44, name: "club8" },
    club9: { index: 4, name: "club9" },
    club10: { index: 51, name: "club10" },
    club11: { index: 32, name: "club11" },
    club12: { index: 28, name: "club12" },
    club13: { index: 46, name: "club13" },

    diamond1: { index: 36, name: "diamond1" },
    diamond2: { index: 23, name: "diamond2" },
    diamond3: { index: 2, name: "diamond3" },
    diamond4: { index: 14, name: "diamond4" },
    diamond5: { index: 50, name: "diamond5" },
    diamond6: { index: 34, name: "diamond6" },
    diamond7: { index: 18, name: "diamond7" },
    diamond8: { index: 8, name: "diamond8" },
    diamond9: { index: 31, name: "diamond9" },
    diamond10: { index: 39, name: "diamond10" },
    diamond11: { index: 48, name: "diamond11" },
    diamond12: { index: 16, name: "diamond12" },
    diamond13: { index: 10, name: "diamond13" }
};



